resume_app/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import *
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('terms-of-service/', terms_of_service, name='terms_of_service'),
    path('login/', login, name='login'),
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('<int:account_id>/logout/', logout, name='logout'),
    path('<int:account_id>/account/', account, name='account'),
    path('<int:account_id>/form/', form, name='form'),
    path('<int:account_id>/reset_password/', reset_password, name='reset_password'),
    path('<int:account_id>/edit_account_name/', edit_account_name, name='edit_account_name'),
    path('<int:account_id>/edit_account_email/', edit_account_email, name='edit_account_email'),
    path('<int:account_id>/confirmation', confirmation, name='confirmation'),
    path('<int:account_id>/reload_resume_and_website', reload_resume_and_website, name='reload_resume_and_website'),
    path('<int:account_id>/reload_resume_and_website_with_job_description', reload_resume_and_website_with_job_description, name='reload_resume_and_website_with_job_description'),
    path('<int:account_id>/build_cover_letter', build_cover_letter, name='build_cover_letter'),
    path('<int:account_id>/subscriptions', subscriptions, name='subscriptions'),
    path('cancel_subscription/<int:account_id>/<str:subscription_id>/', cancel_subscription, name='cancel_subscription'),
    path('payment_successful', payment_successful, name='payment_successful'),
    path('payment_cancelled', payment_cancelled, name='payment_cancelled'),
    path('<str:url_name>/', website, name='website'),
    path('form/CheckUrlNameView/', CheckUrlNameView.as_view(), name='CheckUrlNameView'),
    path('login/CheckAccountNameView/', CheckAccountNameView.as_view(), name='CheckAccountNameView'),
    path('login/CheckAccountEmailView/', CheckAccountEmailView.as_view(), name='CheckAccountEmailView'),
    # Correct URL pattern for terms of service
]



    # path('stripe_webhook/', stripe_webhook, name='stripe_webhook'),

resume_app/models.py
import datetime
import os
from django.conf import settings
from django.db import models
from django.core.validators import MaxLengthValidator, MinLengthValidator
from django.core.exceptions import ValidationError
from django.db import models
import stripe
from datetime import datetime
from django.db import models
from datetime import date
from django.db import models
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from datetime import date
import os


def validate_unique_url_name(value):
    existing_profiles = UserProfile.objects.filter(url_name=value)
    if existing_profiles.exists():
        raise ValidationError('This URL name is already taken. Please choose a different one.')

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

class Account(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='account_user')
    name = models.CharField(max_length=255, unique=True)  # needs to be unique
    password = models.CharField(max_length=255)  # Store hashed password
    email = models.EmailField()
    tier = models.CharField(max_length=255, default="free")
    educations = models.ForeignKey('Education', on_delete=models.SET_NULL, null=True, related_name='education_account')
    user_profile = models.ForeignKey('UserProfile', on_delete=models.SET_NULL, null=True, related_name='user_profile_account')
    user_plan = models.ForeignKey('Plan', on_delete=models.SET_NULL, null=True, related_name='user_plan')
    user_payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, null=True, related_name='user_payment')
    resume_links = models.CharField(max_length=100000, blank=True, null=True, help_text="Separate links with commas")
    unique_words = models.CharField(max_length=10000000, blank=True, null=True, help_text="Separate action words with commas")
    reset_password_code = models.CharField(max_length=255, null=True)
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        # Convert the name to lowercase
        if self.name:
            self.name = self.name.lower()
        
        # Hash the password before saving
        if self.password:
            self.password = make_password(self.password)
        
        super(Account, self).save(*args, **kwargs)

    def get_resume_links(self):
        return self.resume_links.split(',') if self.resume_links else []

    def set_resume_link(self, link):
        links = self.get_resume_links()
        links.append(link)
        self.resume_links = ','.join(links)

    def get_unique_words_list(self):
        return self.unique_words.split(',') if self.unique_words else []

    def add_unique_word(self, word):
        words = self.get_unique_words_list()
        words.append(word)
        self.unique_words = ','.join(words)

    def __str__(self):
        return f"{self.id}: {self.name}"

    def check_password(self, raw_password):
        from django.contrib.auth.hashers import check_password
        return check_password(raw_password, self.password)  # Use check_password to verify a raw password

class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        # If the file already exists, remove it so the new file can be saved
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

class UserProfile(models.Model):

    def profile_image_upload_to(instance, filename):
        return f"profile_pictures/{instance.account.id}.jpg"
    
    id = models.AutoField(primary_key=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, related_name='account_user_profile')
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    linkedin_link = models.CharField(blank=True, null=True, max_length=255)
    resume_link = models.URLField(blank=True, null=True)
    github_link = models.CharField(blank=True, null=True, max_length=255)
    website_link = models.URLField(blank=True, null=True)
    profile_image = models.ImageField(upload_to=profile_image_upload_to, storage=OverwriteStorage(), blank=True, null=True)

    spoken_languages = models.CharField(max_length=255, blank=True, null=True)
    programming_languages = models.CharField(max_length=255, blank=True, null=True)
    technical_skills = models.CharField(max_length=255, blank=True, null=True)
    leadership = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.id}: {self.account}"
    
class Education(models.Model):
    id = models.AutoField(primary_key=True)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, related_name='account_education')
    # user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name='education', default=None)
    institution = models.CharField(max_length=255, blank=True, null=True)
    major = models.CharField(max_length=255, blank=True, null=True)
    minor = models.CharField(max_length=255, blank=True, null=True)
    GPA = models.CharField(max_length=255, blank=True, null=True)
    start_date = models.DateField(default=date.today, null=True)
    end_date = models.DateField(default=date.today, null=True)
    city = models.CharField(max_length=255, blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    current = models.BooleanField(default=False, null=True)  
    coursework = models.CharField(max_length=1000, blank=True, null=True)
    
    DEGREE_CHOICES = [
        # Bachelor's Degrees
        ('Bachelor of Science', 'Bachelor of Science'),
        ('Bachelor of Art', 'Bachelor of Art'),

        # Master's Degrees
        ('Master of Arts', 'Master of Arts'),
        ('Master of Science', 'Master of Science'),
        ('Master of Business Administration', 'Master of Business Administration'),

        # Associate Degrees (Community Colleges)
        ('Associate of Arts', 'Associate of Arts'),
        ('Associate of Science', 'Associate of Science'),
        ('Associate of Business Administration', 'Associate of Business Administration'),
        ('Associate of Engineering', 'Associate of Engineering'),
        ('Associate of Nursing', 'Associate of Nursing'),
    ]


    degree_type = models.CharField(
        max_length=100,
        choices=DEGREE_CHOICES,
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.id}: {self.account}"

class WorkExperience(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, related_name='work_experiences')
    company_name = models.CharField(max_length=255, validators=[MinLengthValidator(1)])
    job_title = models.CharField(max_length=255, validators=[MinLengthValidator(1)])
    start_date = models.DateField()
    end_date = models.DateField(null=True)
    currently_working = models.BooleanField(default=False)  
    city = models.CharField(max_length=255, validators=[MinLengthValidator(1)])
    state = models.CharField(max_length=2, validators=[MinLengthValidator(2), MaxLengthValidator(2)])
    description = models.TextField(validators=[MinLengthValidator(1)])
    bullet1 = models.CharField(max_length=255, validators=[MinLengthValidator(1)])
    bullet2 = models.CharField(max_length=255, validators=[MinLengthValidator(1)])
    bullet3 = models.CharField(max_length=255, validators=[MinLengthValidator(1)])

    def __str__(self):
        return f"Account : {self.account} , {self.company_name}"

class Project(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True, related_name='projects')
    project_name = models.CharField(max_length=255)
    project_skills = models.CharField(max_length=255)
    description = models.TextField()
    bullet1 = models.CharField(max_length=255)
    bullet2 = models.CharField(max_length=255)

    def __str__(self):
        return f"Account : {self.account}"

class Plan(models.Model):
    id = models.AutoField(primary_key=True)
    type = models.CharField(max_length=255, default="free")
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    forms_remaining = models.IntegerField(default=2)
    forms_filled_on_current_plan = models.IntegerField(default=0)
    total_forms_filled = models.IntegerField(default=0)
    total_cover_letters = models.IntegerField(default=0)
    total_tailored_resumes = models.IntegerField(default=0)
    subscription_ids = models.CharField(max_length=100000, blank=True, null=True, help_text="subscription_ids seperated by commas")


    def get_subscription_ids(self):
        return self.subscription_ids.split(',') if self.subscription_ids else []

    def set_subscription_ids(self, subscription_id):
        ids = set(self.get_subscription_ids())  # Use a set to ensure uniqueness
        ids.add(subscription_id)
        self.subscription_ids = ','.join(ids)


    def save(self, *args, **kwargs):
        # Define the mapping of types to forms_remaining values
        type_forms_mapping = {
            'free': 2,
            'basic': 20,
            'economy': 50,
            'business': 100,
            'first_class': 200,
            'pilot': 400,
            'pilot2': 1000,
        }

        # Update forms_remaining based on the type
        self.forms_remaining = type_forms_mapping.get(self.type, 2)

        # Call the original save method to save the changes
        super(Plan, self).save(*args, **kwargs)

    def __str__(self):
            return f"{self.account}"

class Payment(models.Model):

    PAYMENT_MODE_CHOICES = [
        ('payment', 'Payment'),

resume_app/templates/account.html
{% extends 'index.html' %}
{% load static %}


{% block header_links %}
        <a href="{% url 'confirmation' account_id=account.id %}">  Build Page </a>
        <a href="{% url 'subscriptions' account_id=account.id %}">  Orders </a>

{% endblock %}


{% block header_links_nav %}
        <a href="{% url 'confirmation' account_id=account.id %}">  Build Page </a>
        <a href="{% url 'subscriptions' account_id=account.id %}">  Orders </a>

{% endblock %}


{% block content %}


<style>

    /* Error and success messages */
    .error-message {
        color: white;
        background-color: #e74c3c;  /* Red background */
        border: 1px solid #c0392b;  /* Darker red border */
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        width: auto;
    }

    .success-message {
        color: white;
        background-color: #27ae60;  /* Green background */
        border: 1px solid #2ecc71;  /* Darker green border */
        padding: 10px;
        border-radius: 5px;
        font-weight: bold;
        width: auto;
    }

    /* Global styles for dark theme */
    body {
        font-family: 'Arial', sans-serif;
        background-color: #1a1a1a; /* Dark background */
        color: #e0e0e0; /* Light text color */
    }

    h1, h2 {
        color: #f1f1f1; /* Light heading color */
    }

    /* Form styling */
    form {
        background-color: #333333; /* Dark background for forms */
        color: #e0e0e0;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
    }

    label {
        display: block;
        margin: 10px 0 5px;
        color: #e0e0e0;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #555; /* Dark border */
        border-radius: 4px;
        background-color: #444; /* Dark background for inputs */
        color: #e0e0e0;
        box-sizing: border-box;
    }

    button {
        background-color: #ffd60a; /* Blue button color */
        color: white;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #6200ea; /* Darker blue on hover */
    }

    /* Table styling */
    .user-info-table {
        width: auto;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    .user-info-table td {
        padding: 8px;
        border: 1px solid #555; /* Darker border */
        text-align: left;
        color: #e0e0e0;
    }

    .user-info-table tr:nth-child(even) {
        background-color: #444; /* Dark rows */
    }

    .user-info-table tr:hover {
        background-color: #555; /* Highlight row on hover */
    }

    .user-info-table b {
        color: #3498db; /* Blue color for bold text */
    }

    /* Button for rebuilding resume and website */
    .reload_resume_and_website-button, button {
        background-color: #6200ea; /* Blue button */
        color: white;
        border: none;
        padding: 8px 16px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 5px;
        cursor: pointer;
        border-radius: 5px;
    }

    .reload_resume_and_website-button:hover, button:hover {
        background-color: #f39c12; /* Yellow/orange hover color */
    }

    /* Additional styling for links */
    a {
        color: #3498db; /* Blue color for links */
    }

    a:hover {
        color: #f39c12; /* Yellow on hover */
    }

</style>


<div>

<div class="user-info-container">


    <table class="user-info-table">
        <tr>
            <td>Your Tier:</td>
            <td>{{account.tier}}</td>
        </tr>
        <tr>
            <td>Total Created on {{account.tier}}:</td>
            <td>{{user_plan.forms_filled_on_current_plan}}</td>
        </tr>
        <tr>
            <td>Total Tailored Resumes:</td>
            <td>{{user_plan.total_tailored_resumes}} </td>
        </tr>
        <tr>
            <td>Total Cover Letters:</td>
            <td>{{user_plan.total_cover_letters}} </td>
        </tr>
        <tr>
            <td>Total Created on all tiers:</td>
            <td>{{user_plan.total_forms_filled}} </td>
        </tr>
        <tr>
            <td>Remaining:</td>
            <td> <b> {{remaining}} </b> </td>
        </tr>


    </table>

    <a href="{% url 'confirmation' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button"> Build Page </button>
    </a>

    <a href="{% url 'subscriptions' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button">  Orders </button>
    </a>


    <h1>Account Details</h1>
    <p><strong>Account ID:</strong> {{ account.id }}</p>
    <p><strong> Name:</strong> {{ account.name }} <button id="edit-name-btn">Edit Name</button> </p>
    <p><strong> Email:</strong> {{ account.email }}<button id="edit-email-btn">Edit Email</button> </p>

    <form id="edit-email-form" method="post" action="{% url 'edit_account_email' account_id=account.id %}" style="display: none;">
        {% csrf_token %}
        <h2>Edit Email</h2>
        <p>Please enter password for verification.</p>
        
        <label for="id_password_email">Password:</label>
        <input type="password" id="id_password_email" name="password" required>
        
        <p>Enter your new email.</p>
        <label for="id_name">New Email:</label>
        <input type="email" id="id_email" name="email">
        
        <button type="submit">Save</button>
        <button type="button" id="cancel-edit-email">Cancel</button> <!-- Updated ID -->
        
        <br><br>
        
    </form>
    
    
    <form id="edit-name-form" method="post" action="{% url 'edit_account_name' account_id=account.id %}" style="display: none;">
        {% csrf_token %}
        <h2>Edit Name</h2>
        <p>Please enter password for verification.</p>
        
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password" required>
        
        <p>Enter your new name. Your website will be cheesecv.com/name </p>
        <label for="id_name">New Name:</label>
        <input type="text" id="id_name" name="name">
        
        <button type="submit">Save</button>
        <button type="button" id="cancel-edit">Cancel</button> <!-- Updated ID -->
        
        <br><br>
        
    </form>
    
    {% if messages %}
        <ul>
            {% for message in messages %}
            {% if message.tags == 'error' %}
                <li class="error-message">{{ message }}</li>
            {% elif message.tags == 'success' %}
                <li class="success-message">{{ message }}</li>
            {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    
    <script>
        document.getElementById("edit-name-btn").addEventListener("click", function() {
            document.getElementById("edit-name-form").style.display = "block";
        });
    
        document.getElementById("cancel-edit").addEventListener("click", function() {
            document.getElementById("edit-name-form").style.display = "none";
        });
    </script>
    
    <script>
        document.getElementById("edit-email-btn").addEventListener("click", function() {
            document.getElementById("edit-email-form").style.display = "block";
        });
    
        document.getElementById("cancel-edit-email").addEventListener("click", function() {
            document.getElementById("edit-email-form").style.display = "none";
        });
    </script>

    
    <p><strong>All resume links:</strong> 
    {% if account.resume_links %}
    <ol>
        {% for link in account.get_resume_links %}
        <li><a href="{{ link }}" target="_blank">{{ link }}</a></li>
        {% endfor %}
    </ol>
    {% else %}
    <p>No resume links available.</p>
    {% endif %}

    
    


    <h2>User Profile</h2>
    <a href="{% url 'form' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button"> Edit data </button>
    </a>
    
    <ul>
        <li><strong>First Name:</strong> {{ user_profile.first_name }}</li>
        <li><strong>Last Name:</strong> {{ user_profile.last_name }}</li>
        <li><strong>Phone:</strong> {{ user_profile.phone }}</li>
        <li><strong>Email:</strong> {{ user_profile.email }}</li>
        <li><strong>City:</strong> {{ user_profile.city }}</li>
        <li><strong>State:</strong> {{ user_profile.state }}</li>
        <li><strong>LinkedIn Link:</strong> {{ user_profile.linkedin_link }}</li>
        <li><strong>Resume Link:</strong> {{ user_profile.resume_link }}</li>
        <li><strong>GitHub Link:</strong> {{ user_profile.github_link }}</li>
        
        {% if user_profile.profile_image %}
            <li><strong>Profile Image:</strong> <img src="{{ user_profile.profile_image.url }}" alt="Profile Image"></li>
        {% else %}
        <li><strong>Profile Image:</strong> No photo uploaded </li>
        {% endif %}



        <li><strong>Institution:</strong> {{ user_profile.institution }}</li>
        <li><strong>Major:</strong> {{ user_profile.major }}</li>
        <li><strong>Minor:</strong> {{ user_profile.minor }}</li>
        <li><strong>Start Date:</strong> {{ user_profile.start_date }}</li>
        <li><strong>End Date:</strong> {{ user_profile.end_date }}</li>
        <li><strong>Spoken Languages:</strong> {{ user_profile.spoken_languages }}</li>
        <li><strong>Programming Languages:</strong> {{ user_profile.programming_languages }}</li>
        <li><strong>Technical Skills:</strong> {{ user_profile.technical_skills }}</li>
        <li><strong>Leadership:</strong> {{ user_profile.leadership }}</li>
        <li><strong>Degree Type:</strong> {{ user_profile.get_degree_type_display }}</li>
    </ul>

    <h2>Education</h2>
    <a href="{% url 'form' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button"> Edit data </button>
    </a>
    <ul>
        {% for education in educations %}
            <li>
                <strong>Institution:</strong> {{ education.institution }}<br>
                <strong>Degree:</strong> {{ education.degree_type }}<br>
                <strong>Major:</strong> {{ education.major }}<br>
                <strong>Minor:</strong> {{ education.minor }}<br>
                <strong>GPA:</strong> {{ education.GPA }}<br>
                <strong>Start Date:</strong> {{ education.start_date }}<br>
                <strong>End Date:</strong> {{ education.end_date }}<br>
                <strong>City:</strong> {{ education.city }}<br>
                <strong>Country:</strong> {{ education.country }}<br>
                <strong>Current:</strong> {{ education.current }}<br>
                <strong>Coursework:</strong> {{ education.coursework }}
            </li>  <br>
        {% endfor %}
    </ul>
    



    
    <h2>Work Experiences</h2>
    <a href="{% url 'form' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button"> Edit data </button>
    </a>
    <ul>
            {% for work_experience in work_experiences %}
                <li>
                    <strong>Company Name:</strong> {{ work_experience.company_name }}<br>
                    <strong>Job title:</strong> {{ work_experience.job_title }}<br>
                    <strong>Start Date:</strong> {{ work_experience.start_date }}<br>
                    <strong>End Date:</strong> {{ work_experience.end_date }}<br>
                    <strong>City:</strong> {{ work_experience.city }}<br>
                    <strong>State:</strong> {{ work_experience.state }}<br>
                    <strong>Description:</strong> {{ work_experience.description }}<br>
                    <strong>Bullet 1:</strong> {{ work_experience.bullet1 }}<br>
                    <strong>Bullet 2:</strong> {{ work_experience.bullet2 }}<br>
                    <strong>Bullet 3:</strong> {{ work_experience.bullet3 }}
                </li>
                <br>
            {% endfor %}
    </ul>


    <h2>Projects</h2>
    <a href="{% url 'form' account_id=account.id %}" class="reload_resume_and_website-button">
        <button type="button"> Edit data </button>
    </a>
    <ul>
        {% for project in projects %}
            <li>
                <strong>Project Name:</strong> {{ project.project_name }}<br>
                <strong>Project Skills:</strong> {{ project.project_skills }}<br>
                <strong>Description:</strong> {{ project.description }}<br>
                <strong>Bullet 1:</strong> {{ project.bullet1 }}<br>
                <strong>Bullet 2:</strong> {{ project.bullet2 }}
            </li>
            <br>
        {% endfor %}
    </ul>
    
</div>

{% endblock %}





       

resume_app/templates/new_account_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to CheeseCV</title>
</head>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 20px auto;">
        <h2>{{ account.name }}, Welcome To CheeseCV !</h2>
        <p>
            We're thrilled to have you as a part of CheeseCV. Your account has been successfully created.
        </p>
        <p>
            Here are your account details:
            <ul>
                <li><strong>Name:</strong> {{ account.name }}</li>
                <li><strong>Email:</strong> {{ account.email }}</li>
            </ul>
        </p>
        <p>
            With CheeseCV, you have access to the following services:
            <ul>
                <li>Fill in a form and we'll build you a resume and website in 30 seconds</li>
                <li>Generate a tailored resume for a specific job description in  30 seconds</li>
                <li>Create a customized cover letter for a job description in 30 seconds</li>
            </ul>
        </p>
        <p>
            Thank you for choosing CheeseCV. If you have any questions or need assistance, feel free to contact us.
        </p>
        <p>
            Best regards,<br>
            The CheeseCV Team
        </p>
    </div>
</body>
</html>

resume_app/templates/reset_password.html
{% extends 'index.html' %}
{% block content %}

<style>

    .error-message {
        color: white;
        background-color: #ff3333;  /* Red background color */
        border: 1px solid #cc0000;  /* Darker red border color */
        padding: 10px;  /* Adjust the padding as needed */
        border-radius: 5px;  /* Rounded corners */
        font-weight: bold;  /* Bold text */
        margin: 10px auto; /* Center the messages horizontally */

    }

    .success-message {
    color: white;
    background-color: green;  /* Green background color */
    border: 1px solid green;  /* Darker green border color */
    padding: 10px;  /* Adjust the padding as needed */
    border-radius: 5px;  /* Rounded corners */
    font-weight: bold;  /* Bold text */
    margin: 10px auto; /* Center the messages horizontally */

    }

</style>

<style>

    body {
        font-family: 'Arial', sans-serif;
        background-color: #f2f2f2; /* Light gray background */
        margin: 0;
        padding: 0;
    }

    h1 {
        text-align: center;
        color: #333333; /* Dark gray text color */
    }

    form {
        max-width: 400px;
        margin: 300px auto; /* Adjusted margin for better spacing */
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    label {
        display: block;
        margin: 10px 0 5px;
        color: #333333;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #cccccc; /* Light gray border */
        border-radius: 4px;
        box-sizing: border-box;
    }

    button {
        background-color: #007bff; /* Blue button color */
        color: #ffffff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #0056b3; /* Darker blue on hover */
    }

</style>




<form method="post" action="{% url 'reset_password' account_id=account.id %}">
    {% csrf_token %}
    
    <h1>Reset Password for {{ account.name }}</h1>

    <label for="id_new_password">Verification code:</label>
    <input type="text" id="id_verification_code" name="verification_code" required>

    <label for="id_new_password">New Password:</label>
    <input type="password" id="id_new_password" name="new_password" required>
    
    <br>

    <label for="id_confirm_new_password">Confirm New Password:</label>
    <input type="password" id="id_confirm_new_password" name="confirm_new_password" required>

    <br>

    <button type="submit">Reset Password</button>

    {% if messages %}
    <ul>
        {% for message in messages %}
        {% if message.tags == 'error' %}
            <li class="error-message">{{ message }}</li>
        {% elif message.tags == 'success' %}
            <li class="success-message">{{ message }}</li>
        {% endif %}
        {% endfor %}
    </ul>
    {% endif %}
</form>

{% endblock %}